/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ContactSettings { 'email' : string, 'phone' : string }
export type DevelopmentId = bigint;
export interface DevelopmentInput {
  'status' : DevelopmentStatus,
  'title' : string,
  'description' : string,
  'photo' : [] | [ExternalBlob],
  'budget' : bigint,
}
export type DevelopmentStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'ongoing' : null };
export interface DevelopmentUpdate {
  'id' : DevelopmentId,
  'status' : DevelopmentStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'photo' : [] | [ExternalBlob],
  'budget' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface GeoLocation { 'latitude' : number, 'longitude' : number }
export interface OfficialResponse {
  'id' : ResponseId,
  'createdAt' : Timestamp,
  'problemId' : ProblemId,
  'message' : string,
}
export interface Problem {
  'id' : ProblemId,
  'upvotes' : bigint,
  'status' : ProblemStatus,
  'title' : string,
  'reporterName' : [] | [string],
  'reporterContact' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'category' : ProblemCategory,
  'photo' : [] | [ExternalBlob],
  'location' : [] | [GeoLocation],
}
export type ProblemCategory = { 'other' : null } |
  { 'road' : null } |
  { 'education' : null } |
  { 'electricity' : null } |
  { 'sanitation' : null } |
  { 'water' : null } |
  { 'health' : null };
export interface ProblemDetail {
  'responses' : Array<OfficialResponse>,
  'statusHistory' : Array<StatusChange>,
  'problem' : Problem,
}
export interface ProblemFilter {
  'status' : [] | [ProblemStatus],
  'search' : [] | [string],
  'category' : [] | [ProblemCategory],
}
export type ProblemId = bigint;
export interface ProblemInput {
  'title' : string,
  'reporterName' : [] | [string],
  'reporterContact' : [] | [string],
  'description' : string,
  'category' : ProblemCategory,
  'photo' : [] | [ExternalBlob],
  'location' : [] | [GeoLocation],
}
export interface ProblemStats {
  'resolved' : bigint,
  'total' : bigint,
  'open' : bigint,
  'byCategory' : Array<[ProblemCategory, bigint]>,
}
export type ProblemStatus = { 'new' : null } |
  { 'resolved' : null } |
  { 'inProgress' : null };
export type ResponseId = bigint;
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface StatusChange {
  'changedAt' : Timestamp,
  'toStatus' : ProblemStatus,
  'fromStatus' : ProblemStatus,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface VillageDashboard {
  'developmentCount' : bigint,
  'ongoingCount' : bigint,
  'completedCount' : bigint,
  'profile' : [] | [VillageProfile],
}
export interface VillageProfile {
  'name' : string,
  'updatedAt' : Timestamp,
  'areaSqKm' : number,
  'facilities' : Array<string>,
  'population' : bigint,
  'households' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addOfficialResponse' : ActorMethod<
    [ProblemId, string],
    [] | [OfficialResponse]
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDevelopmentUpdate' : ActorMethod<
    [DevelopmentInput],
    DevelopmentUpdate
  >,
  'createProblem' : ActorMethod<[ProblemInput], Problem>,
  'deleteDevelopmentUpdate' : ActorMethod<[DevelopmentId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSettings' : ActorMethod<[], ContactSettings>,
  'getDevelopmentUpdate' : ActorMethod<
    [DevelopmentId],
    [] | [DevelopmentUpdate]
  >,
  'getProblem' : ActorMethod<[ProblemId], [] | [Problem]>,
  'getProblemDetail' : ActorMethod<[ProblemId], [] | [ProblemDetail]>,
  'getProblemStats' : ActorMethod<[], ProblemStats>,
  'getVillageDashboard' : ActorMethod<[], VillageDashboard>,
  'getVillageProfile' : ActorMethod<[], [] | [VillageProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDevelopmentUpdates' : ActorMethod<[], Array<DevelopmentUpdate>>,
  'listProblems' : ActorMethod<[ProblemFilter], Array<Problem>>,
  'schema' : ActorMethod<[], string>,
  'setVillageProfile' : ActorMethod<[VillageProfile], VillageProfile>,
  'updateContactSettings' : ActorMethod<[string, string], ContactSettings>,
  'updateDevelopmentUpdate' : ActorMethod<
    [DevelopmentId, DevelopmentInput],
    [] | [DevelopmentUpdate]
  >,
  'updateProblemStatus' : ActorMethod<
    [ProblemId, ProblemStatus],
    [] | [Problem]
  >,
  'upvoteProblem' : ActorMethod<[ProblemId], [] | [bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];