/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ProblemId = IDL.Nat;
export const ResponseId = IDL.Nat;
export const Timestamp = IDL.Int;
export const OfficialResponse = IDL.Record({
  'id' : ResponseId,
  'createdAt' : Timestamp,
  'problemId' : ProblemId,
  'message' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DevelopmentStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DevelopmentInput = IDL.Record({
  'status' : DevelopmentStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'budget' : IDL.Nat,
});
export const DevelopmentId = IDL.Nat;
export const DevelopmentUpdate = IDL.Record({
  'id' : DevelopmentId,
  'status' : DevelopmentStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'photo' : IDL.Opt(ExternalBlob),
  'budget' : IDL.Nat,
});
export const ProblemCategory = IDL.Variant({
  'other' : IDL.Null,
  'road' : IDL.Null,
  'education' : IDL.Null,
  'electricity' : IDL.Null,
  'sanitation' : IDL.Null,
  'water' : IDL.Null,
  'health' : IDL.Null,
});
export const GeoLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ProblemInput = IDL.Record({
  'title' : IDL.Text,
  'reporterName' : IDL.Opt(IDL.Text),
  'reporterContact' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'category' : ProblemCategory,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(GeoLocation),
});
export const ProblemStatus = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Problem = IDL.Record({
  'id' : ProblemId,
  'upvotes' : IDL.Nat,
  'status' : ProblemStatus,
  'title' : IDL.Text,
  'reporterName' : IDL.Opt(IDL.Text),
  'reporterContact' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'category' : ProblemCategory,
  'photo' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(GeoLocation),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ContactSettings = IDL.Record({
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const StatusChange = IDL.Record({
  'changedAt' : Timestamp,
  'toStatus' : ProblemStatus,
  'fromStatus' : ProblemStatus,
});
export const ProblemDetail = IDL.Record({
  'responses' : IDL.Vec(OfficialResponse),
  'statusHistory' : IDL.Vec(StatusChange),
  'problem' : Problem,
});
export const ProblemStats = IDL.Record({
  'resolved' : IDL.Nat,
  'total' : IDL.Nat,
  'open' : IDL.Nat,
  'byCategory' : IDL.Vec(IDL.Tuple(ProblemCategory, IDL.Nat)),
});
export const VillageProfile = IDL.Record({
  'name' : IDL.Text,
  'updatedAt' : Timestamp,
  'areaSqKm' : IDL.Float64,
  'facilities' : IDL.Vec(IDL.Text),
  'population' : IDL.Nat,
  'households' : IDL.Nat,
});
export const VillageDashboard = IDL.Record({
  'developmentCount' : IDL.Nat,
  'ongoingCount' : IDL.Nat,
  'completedCount' : IDL.Nat,
  'profile' : IDL.Opt(VillageProfile),
});
export const ProblemFilter = IDL.Record({
  'status' : IDL.Opt(ProblemStatus),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ProblemCategory),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addOfficialResponse' : IDL.Func(
      [ProblemId, IDL.Text],
      [IDL.Opt(OfficialResponse)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDevelopmentUpdate' : IDL.Func(
      [DevelopmentInput],
      [DevelopmentUpdate],
      [],
    ),
  'createProblem' : IDL.Func([ProblemInput], [Problem], []),
  'deleteDevelopmentUpdate' : IDL.Func([DevelopmentId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSettings' : IDL.Func([], [ContactSettings], ['query']),
  'getDevelopmentUpdate' : IDL.Func(
      [DevelopmentId],
      [IDL.Opt(DevelopmentUpdate)],
      ['query'],
    ),
  'getProblem' : IDL.Func([ProblemId], [IDL.Opt(Problem)], ['query']),
  'getProblemDetail' : IDL.Func(
      [ProblemId],
      [IDL.Opt(ProblemDetail)],
      ['query'],
    ),
  'getProblemStats' : IDL.Func([], [ProblemStats], ['query']),
  'getVillageDashboard' : IDL.Func([], [VillageDashboard], ['query']),
  'getVillageProfile' : IDL.Func([], [IDL.Opt(VillageProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDevelopmentUpdates' : IDL.Func(
      [],
      [IDL.Vec(DevelopmentUpdate)],
      ['query'],
    ),
  'listProblems' : IDL.Func([ProblemFilter], [IDL.Vec(Problem)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setVillageProfile' : IDL.Func([VillageProfile], [VillageProfile], []),
  'updateContactSettings' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ContactSettings],
      [],
    ),
  'updateDevelopmentUpdate' : IDL.Func(
      [DevelopmentId, DevelopmentInput],
      [IDL.Opt(DevelopmentUpdate)],
      [],
    ),
  'updateProblemStatus' : IDL.Func(
      [ProblemId, ProblemStatus],
      [IDL.Opt(Problem)],
      [],
    ),
  'upvoteProblem' : IDL.Func([ProblemId], [IDL.Opt(IDL.Nat)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ProblemId = IDL.Nat;
  const ResponseId = IDL.Nat;
  const Timestamp = IDL.Int;
  const OfficialResponse = IDL.Record({
    'id' : ResponseId,
    'createdAt' : Timestamp,
    'problemId' : ProblemId,
    'message' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DevelopmentStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DevelopmentInput = IDL.Record({
    'status' : DevelopmentStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'budget' : IDL.Nat,
  });
  const DevelopmentId = IDL.Nat;
  const DevelopmentUpdate = IDL.Record({
    'id' : DevelopmentId,
    'status' : DevelopmentStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'photo' : IDL.Opt(ExternalBlob),
    'budget' : IDL.Nat,
  });
  const ProblemCategory = IDL.Variant({
    'other' : IDL.Null,
    'road' : IDL.Null,
    'education' : IDL.Null,
    'electricity' : IDL.Null,
    'sanitation' : IDL.Null,
    'water' : IDL.Null,
    'health' : IDL.Null,
  });
  const GeoLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ProblemInput = IDL.Record({
    'title' : IDL.Text,
    'reporterName' : IDL.Opt(IDL.Text),
    'reporterContact' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'category' : ProblemCategory,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(GeoLocation),
  });
  const ProblemStatus = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Problem = IDL.Record({
    'id' : ProblemId,
    'upvotes' : IDL.Nat,
    'status' : ProblemStatus,
    'title' : IDL.Text,
    'reporterName' : IDL.Opt(IDL.Text),
    'reporterContact' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'category' : ProblemCategory,
    'photo' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(GeoLocation),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ContactSettings = IDL.Record({
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StatusChange = IDL.Record({
    'changedAt' : Timestamp,
    'toStatus' : ProblemStatus,
    'fromStatus' : ProblemStatus,
  });
  const ProblemDetail = IDL.Record({
    'responses' : IDL.Vec(OfficialResponse),
    'statusHistory' : IDL.Vec(StatusChange),
    'problem' : Problem,
  });
  const ProblemStats = IDL.Record({
    'resolved' : IDL.Nat,
    'total' : IDL.Nat,
    'open' : IDL.Nat,
    'byCategory' : IDL.Vec(IDL.Tuple(ProblemCategory, IDL.Nat)),
  });
  const VillageProfile = IDL.Record({
    'name' : IDL.Text,
    'updatedAt' : Timestamp,
    'areaSqKm' : IDL.Float64,
    'facilities' : IDL.Vec(IDL.Text),
    'population' : IDL.Nat,
    'households' : IDL.Nat,
  });
  const VillageDashboard = IDL.Record({
    'developmentCount' : IDL.Nat,
    'ongoingCount' : IDL.Nat,
    'completedCount' : IDL.Nat,
    'profile' : IDL.Opt(VillageProfile),
  });
  const ProblemFilter = IDL.Record({
    'status' : IDL.Opt(ProblemStatus),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ProblemCategory),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addOfficialResponse' : IDL.Func(
        [ProblemId, IDL.Text],
        [IDL.Opt(OfficialResponse)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDevelopmentUpdate' : IDL.Func(
        [DevelopmentInput],
        [DevelopmentUpdate],
        [],
      ),
    'createProblem' : IDL.Func([ProblemInput], [Problem], []),
    'deleteDevelopmentUpdate' : IDL.Func([DevelopmentId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSettings' : IDL.Func([], [ContactSettings], ['query']),
    'getDevelopmentUpdate' : IDL.Func(
        [DevelopmentId],
        [IDL.Opt(DevelopmentUpdate)],
        ['query'],
      ),
    'getProblem' : IDL.Func([ProblemId], [IDL.Opt(Problem)], ['query']),
    'getProblemDetail' : IDL.Func(
        [ProblemId],
        [IDL.Opt(ProblemDetail)],
        ['query'],
      ),
    'getProblemStats' : IDL.Func([], [ProblemStats], ['query']),
    'getVillageDashboard' : IDL.Func([], [VillageDashboard], ['query']),
    'getVillageProfile' : IDL.Func([], [IDL.Opt(VillageProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDevelopmentUpdates' : IDL.Func(
        [],
        [IDL.Vec(DevelopmentUpdate)],
        ['query'],
      ),
    'listProblems' : IDL.Func([ProblemFilter], [IDL.Vec(Problem)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setVillageProfile' : IDL.Func([VillageProfile], [VillageProfile], []),
    'updateContactSettings' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ContactSettings],
        [],
      ),
    'updateDevelopmentUpdate' : IDL.Func(
        [DevelopmentId, DevelopmentInput],
        [IDL.Opt(DevelopmentUpdate)],
        [],
      ),
    'updateProblemStatus' : IDL.Func(
        [ProblemId, ProblemStatus],
        [IDL.Opt(Problem)],
        [],
      ),
    'upvoteProblem' : IDL.Func([ProblemId], [IDL.Opt(IDL.Nat)], []),
  });
};

export const init = ({ IDL }) => { return []; };