/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface ContactSettings {
    email: string;
    phone: string;
}
export type DevelopmentId = bigint;
export interface DevelopmentInput {
    status: DevelopmentStatus;
    title: string;
    description: string;
    photo?: ExternalBlob;
    budget: bigint;
}
export interface DevelopmentUpdate {
    id: DevelopmentId;
    status: DevelopmentStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    photo?: ExternalBlob;
    budget: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface GeoLocation {
    latitude: number;
    longitude: number;
}
export interface OfficialResponse {
    id: ResponseId;
    createdAt: Timestamp;
    problemId: ProblemId;
    message: string;
}
export interface Problem {
    id: ProblemId;
    upvotes: bigint;
    status: ProblemStatus;
    title: string;
    reporterName?: string;
    reporterContact?: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: ProblemCategory;
    photo?: ExternalBlob;
    location?: GeoLocation;
}
export interface ProblemDetail {
    responses: Array<OfficialResponse>;
    statusHistory: Array<StatusChange>;
    problem: Problem;
}
export interface ProblemFilter {
    status?: ProblemStatus;
    search?: string;
    category?: ProblemCategory;
}
export type ProblemId = bigint;
export interface ProblemInput {
    title: string;
    reporterName?: string;
    reporterContact?: string;
    description: string;
    category: ProblemCategory;
    photo?: ExternalBlob;
    location?: GeoLocation;
}
export interface ProblemStats {
    resolved: bigint;
    total: bigint;
    open: bigint;
    byCategory: Array<[ProblemCategory, bigint]>;
}
export type ResponseId = bigint;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface StatusChange {
    changedAt: Timestamp;
    toStatus: ProblemStatus;
    fromStatus: ProblemStatus;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface VillageDashboard {
    developmentCount: bigint;
    ongoingCount: bigint;
    completedCount: bigint;
    profile?: VillageProfile;
}
export interface VillageProfile {
    name: string;
    updatedAt: Timestamp;
    areaSqKm: number;
    facilities: Array<string>;
    population: bigint;
    households: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DevelopmentStatus {
    completed = "completed",
    planned = "planned",
    ongoing = "ongoing"
}
export enum ProblemCategory {
    other = "other",
    road = "road",
    education = "education",
    electricity = "electricity",
    sanitation = "sanitation",
    water = "water",
    health = "health"
}
export enum ProblemStatus {
    new = "new",
    resolved = "resolved",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addOfficialResponse(id: ProblemId, message: string): Promise<OfficialResponse | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDevelopmentUpdate(input: DevelopmentInput): Promise<DevelopmentUpdate>;
    createProblem(input: ProblemInput): Promise<Problem>;
    deleteDevelopmentUpdate(id: DevelopmentId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSettings(): Promise<ContactSettings>;
    getDevelopmentUpdate(id: DevelopmentId): Promise<DevelopmentUpdate | null>;
    getProblem(id: ProblemId): Promise<Problem | null>;
    getProblemDetail(id: ProblemId): Promise<ProblemDetail | null>;
    getProblemStats(): Promise<ProblemStats>;
    getVillageDashboard(): Promise<VillageDashboard>;
    getVillageProfile(): Promise<VillageProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listDevelopmentUpdates(): Promise<Array<DevelopmentUpdate>>;
    listProblems(filter: ProblemFilter): Promise<Array<Problem>>;
    schema(): Promise<string>;
    setVillageProfile(input: VillageProfile): Promise<VillageProfile>;
    updateContactSettings(email: string, phone: string): Promise<ContactSettings>;
    updateDevelopmentUpdate(id: DevelopmentId, input: DevelopmentInput): Promise<DevelopmentUpdate | null>;
    updateProblemStatus(id: ProblemId, status: ProblemStatus): Promise<Problem | null>;
    upvoteProblem(id: ProblemId): Promise<bigint | null>;
}
import type { Cell as _Cell, DevelopmentId as _DevelopmentId, DevelopmentInput as _DevelopmentInput, DevelopmentStatus as _DevelopmentStatus, DevelopmentUpdate as _DevelopmentUpdate, Error as _Error, ExternalBlob as _ExternalBlob, GeoLocation as _GeoLocation, OfficialResponse as _OfficialResponse, Problem as _Problem, ProblemCategory as _ProblemCategory, ProblemDetail as _ProblemDetail, ProblemFilter as _ProblemFilter, ProblemId as _ProblemId, ProblemInput as _ProblemInput, ProblemStats as _ProblemStats, ProblemStatus as _ProblemStatus, Result as _Result, Result__1 as _Result__1, StatusChange as _StatusChange, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, VillageDashboard as _VillageDashboard, VillageProfile as _VillageProfile, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addOfficialResponse(arg0: ProblemId, arg1: string): Promise<OfficialResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addOfficialResponse(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOfficialResponse(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDevelopmentUpdate(arg0: DevelopmentInput): Promise<DevelopmentUpdate> {
        if (this.processError) {
            try {
                const result = await this.actor.createDevelopmentUpdate(await to_candid_DevelopmentInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DevelopmentUpdate_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDevelopmentUpdate(await to_candid_DevelopmentInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DevelopmentUpdate_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProblem(arg0: ProblemInput): Promise<Problem> {
        if (this.processError) {
            try {
                const result = await this.actor.createProblem(await to_candid_ProblemInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Problem_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProblem(await to_candid_ProblemInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Problem_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDevelopmentUpdate(arg0: DevelopmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDevelopmentUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDevelopmentUpdate(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSettings(): Promise<ContactSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSettings();
            return result;
        }
    }
    async getDevelopmentUpdate(arg0: DevelopmentId): Promise<DevelopmentUpdate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevelopmentUpdate(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevelopmentUpdate(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProblem(arg0: ProblemId): Promise<Problem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblem(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblem(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProblemDetail(arg0: ProblemId): Promise<ProblemDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblemDetail(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblemDetail(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProblemStats(): Promise<ProblemStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblemStats();
                return from_candid_ProblemStats_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblemStats();
            return from_candid_ProblemStats_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVillageDashboard(): Promise<VillageDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getVillageDashboard();
                return from_candid_VillageDashboard_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVillageDashboard();
            return from_candid_VillageDashboard_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVillageProfile(): Promise<VillageProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVillageProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVillageProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDevelopmentUpdates(): Promise<Array<DevelopmentUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDevelopmentUpdates();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDevelopmentUpdates();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProblems(arg0: ProblemFilter): Promise<Array<Problem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProblems(to_candid_ProblemFilter_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProblems(to_candid_ProblemFilter_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setVillageProfile(arg0: VillageProfile): Promise<VillageProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.setVillageProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVillageProfile(arg0);
            return result;
        }
    }
    async updateContactSettings(arg0: string, arg1: string): Promise<ContactSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactSettings(arg0, arg1);
            return result;
        }
    }
    async updateDevelopmentUpdate(arg0: DevelopmentId, arg1: DevelopmentInput): Promise<DevelopmentUpdate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDevelopmentUpdate(arg0, await to_candid_DevelopmentInput_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDevelopmentUpdate(arg0, await to_candid_DevelopmentInput_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProblemStatus(arg0: ProblemId, arg1: ProblemStatus): Promise<Problem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProblemStatus(arg0, to_candid_ProblemStatus_n59(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProblemStatus(arg0, to_candid_ProblemStatus_n59(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async upvoteProblem(arg0: ProblemId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteProblem(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteProblem(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_DevelopmentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DevelopmentStatus): DevelopmentStatus {
    return "completed" in value ? DevelopmentStatus.completed : "planned" in value ? DevelopmentStatus.planned : "ongoing" in value ? DevelopmentStatus.ongoing : value;
}
async function from_candid_DevelopmentUpdate_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DevelopmentUpdate): Promise<DevelopmentUpdate> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ProblemCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProblemCategory): ProblemCategory {
    return "other" in value ? ProblemCategory.other : "road" in value ? ProblemCategory.road : "education" in value ? ProblemCategory.education : "electricity" in value ? ProblemCategory.electricity : "sanitation" in value ? ProblemCategory.sanitation : "water" in value ? ProblemCategory.water : "health" in value ? ProblemCategory.health : value;
}
async function from_candid_ProblemDetail_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProblemDetail): Promise<ProblemDetail> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_ProblemStats_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProblemStats): ProblemStats {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_ProblemStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProblemStatus): ProblemStatus {
    return "new" in value ? ProblemStatus.new : "resolved" in value ? ProblemStatus.resolved : "inProgress" in value ? ProblemStatus.inProgress : value;
}
async function from_candid_Problem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Problem): Promise<Problem> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_StatusChange_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusChange): StatusChange {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VillageDashboard_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VillageDashboard): VillageDashboard {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfficialResponse]): OfficialResponse | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeoLocation]): GeoLocation | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DevelopmentUpdate]): Promise<DevelopmentUpdate | null> {
    return value.length === 0 ? null : await from_candid_DevelopmentUpdate_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Problem]): Promise<Problem | null> {
    return value.length === 0 ? null : await from_candid_Problem_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProblemDetail]): Promise<ProblemDetail | null> {
    return value.length === 0 ? null : await from_candid_ProblemDetail_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VillageProfile]): VillageProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DevelopmentId;
    status: _DevelopmentStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    photo: [] | [_ExternalBlob];
    budget: bigint;
}): Promise<{
    id: DevelopmentId;
    status: DevelopmentStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    photo?: ExternalBlob;
    budget: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_DevelopmentStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        photo: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.photo)),
        budget: value.budget
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProblemId;
    upvotes: bigint;
    status: _ProblemStatus;
    title: string;
    reporterName: [] | [string];
    reporterContact: [] | [string];
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    category: _ProblemCategory;
    photo: [] | [_ExternalBlob];
    location: [] | [_GeoLocation];
}): Promise<{
    id: ProblemId;
    upvotes: bigint;
    status: ProblemStatus;
    title: string;
    reporterName?: string;
    reporterContact?: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    category: ProblemCategory;
    photo?: ExternalBlob;
    location?: GeoLocation;
}> {
    return {
        id: value.id,
        upvotes: value.upvotes,
        status: from_candid_ProblemStatus_n28(_uploadFile, _downloadFile, value.status),
        title: value.title,
        reporterName: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.reporterName)),
        reporterContact: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.reporterContact)),
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        category: from_candid_ProblemCategory_n30(_uploadFile, _downloadFile, value.category),
        photo: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.photo)),
        location: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n34(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n38(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    responses: Array<_OfficialResponse>;
    statusHistory: Array<_StatusChange>;
    problem: _Problem;
}): Promise<{
    responses: Array<OfficialResponse>;
    statusHistory: Array<StatusChange>;
    problem: Problem;
}> {
    return {
        responses: value.responses,
        statusHistory: from_candid_vec_n46(_uploadFile, _downloadFile, value.statusHistory),
        problem: await from_candid_Problem_n26(_uploadFile, _downloadFile, value.problem)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    changedAt: _Timestamp;
    toStatus: _ProblemStatus;
    fromStatus: _ProblemStatus;
}): {
    changedAt: Timestamp;
    toStatus: ProblemStatus;
    fromStatus: ProblemStatus;
} {
    return {
        changedAt: value.changedAt,
        toStatus: from_candid_ProblemStatus_n28(_uploadFile, _downloadFile, value.toStatus),
        fromStatus: from_candid_ProblemStatus_n28(_uploadFile, _downloadFile, value.fromStatus)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: bigint;
    total: bigint;
    open: bigint;
    byCategory: Array<[_ProblemCategory, bigint]>;
}): {
    resolved: bigint;
    total: bigint;
    open: bigint;
    byCategory: Array<[ProblemCategory, bigint]>;
} {
    return {
        resolved: value.resolved,
        total: value.total,
        open: value.open,
        byCategory: from_candid_vec_n51(_uploadFile, _downloadFile, value.byCategory)
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    developmentCount: bigint;
    ongoingCount: bigint;
    completedCount: bigint;
    profile: [] | [_VillageProfile];
}): {
    developmentCount: bigint;
    ongoingCount: bigint;
    completedCount: bigint;
    profile?: VillageProfile;
} {
    return {
        developmentCount: value.developmentCount,
        ongoingCount: value.ongoingCount,
        completedCount: value.completedCount,
        profile: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_tuple_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProblemCategory, bigint]): [ProblemCategory, bigint] {
    return [
        from_candid_ProblemCategory_n30(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusChange>): Array<StatusChange> {
    return value.map((x)=>from_candid_StatusChange_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProblemCategory, bigint]>): Array<[ProblemCategory, bigint]> {
    return value.map((x)=>from_candid_tuple_n52(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DevelopmentUpdate>): Promise<Array<DevelopmentUpdate>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DevelopmentUpdate_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Problem>): Promise<Array<Problem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Problem_n26(_uploadFile, _downloadFile, x)));
}
async function to_candid_DevelopmentInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DevelopmentInput): Promise<_DevelopmentInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_DevelopmentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DevelopmentStatus): _DevelopmentStatus {
    return value == DevelopmentStatus.completed ? {
        completed: null
    } : value == DevelopmentStatus.planned ? {
        planned: null
    } : value == DevelopmentStatus.ongoing ? {
        ongoing: null
    } : value;
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProblemCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProblemCategory): _ProblemCategory {
    return value == ProblemCategory.other ? {
        other: null
    } : value == ProblemCategory.road ? {
        road: null
    } : value == ProblemCategory.education ? {
        education: null
    } : value == ProblemCategory.electricity ? {
        electricity: null
    } : value == ProblemCategory.sanitation ? {
        sanitation: null
    } : value == ProblemCategory.water ? {
        water: null
    } : value == ProblemCategory.health ? {
        health: null
    } : value;
}
function to_candid_ProblemFilter_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProblemFilter): _ProblemFilter {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function to_candid_ProblemInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProblemInput): Promise<_ProblemInput> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ProblemStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProblemStatus): _ProblemStatus {
    return value == ProblemStatus.new ? {
        new: null
    } : value == ProblemStatus.resolved ? {
        resolved: null
    } : value == ProblemStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: DevelopmentStatus;
    title: string;
    description: string;
    photo?: ExternalBlob;
    budget: bigint;
}): Promise<{
    status: _DevelopmentStatus;
    title: string;
    description: string;
    photo: [] | [_ExternalBlob];
    budget: bigint;
}> {
    return {
        status: to_candid_DevelopmentStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        budget: value.budget
    };
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    reporterName?: string;
    reporterContact?: string;
    description: string;
    category: ProblemCategory;
    photo?: ExternalBlob;
    location?: GeoLocation;
}): Promise<{
    title: string;
    reporterName: [] | [string];
    reporterContact: [] | [string];
    description: string;
    category: _ProblemCategory;
    photo: [] | [_ExternalBlob];
    location: [] | [_GeoLocation];
}> {
    return {
        title: value.title,
        reporterName: value.reporterName ? candid_some(value.reporterName) : candid_none(),
        reporterContact: value.reporterContact ? candid_some(value.reporterContact) : candid_none(),
        description: value.description,
        category: to_candid_ProblemCategory_n25(_uploadFile, _downloadFile, value.category),
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ProblemStatus;
    search?: string;
    category?: ProblemCategory;
}): {
    status: [] | [_ProblemStatus];
    search: [] | [string];
    category: [] | [_ProblemCategory];
} {
    return {
        status: value.status ? candid_some(to_candid_ProblemStatus_n59(_uploadFile, _downloadFile, value.status)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        category: value.category ? candid_some(to_candid_ProblemCategory_n25(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
